version: '1'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: appointment_db
        MYSQL_USER: admin
        MYSQL_PASSWORD: 1234
    ports:
      - "33061:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local